name: Android CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  build:
    name: Build, Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew test --stacktrace

      - name: Run lint
        run: ./gradlew lintDevDebug --stacktrace

      - name: Build debug APK
        run: ./gradlew assembleDevDebug --stacktrace

      - name: Upload dev Debug APK
        uses: actions/upload-artifact/@v7
        with:
          name: stockDemo-dev-apk
          path: app/build/outputs/apk/dev/debug/*.apk
          retention-days: 7

      - name: Upload lint report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: lint-report
          path: app/build/reports/lint-results-devDebug.html
          retention-days: 7

