name: Android CI

on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: checkout source code
        uses: actions/checkout@v4

      - name: set up SDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-provider: basic
      - name: make gradlew executable
        run: chmod +x ./gradlew

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Run lint
        run: ./gradlew lintDebug

      - name: Build debug APK
        run: ./gradlew assembleDebug



